### PR TITLE
Add graphics from presentation to git

### PR DESCRIPTION
**Pull request by Tecklenburg**
Add the graphics from the presentation to git

Issue fix: #301

### CODE REVIEW

**Review by emedema — CHANGES_REQUESTED** [review]
again notes on what you did would be fine but I don't think we should add screenshots of code that would already be in the repo

**Review by rogov-dvp — COMMENTED** [review]
Hmm, I'm not sure if we really need this in the repo :/

**Comment by Tecklenburg** [comment]
Fair point, adjusted it :)

**Review by emedema — APPROVED** [review]
looks good!

**Review by rogov-dvp — APPROVED** [review]
Yes!! :D

**Pull request merged**
