### PR TITLE
Data cleaning tests 

### PR DESCRIPTION
**Pull request by marieke6**
Implemented tests required for data cleaning script

Issue fix: #190 

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have merge this code with the most updated version of main branch
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes
- [x] I have set the Reviewers, Assignee, Labels, Projects, Milestones, and Linked Issues on my PR

### CODE REVIEW

**Review by emedema — APPROVED** [review]
nice job on the testing :)

**Review by rogov-dvp — APPROVED** [review]
Nice job Marieke!

**Review by Tecklenburg — APPROVED** [review]
Does the lower file actually run? The indentation looks strange in line 17-19?

Otherwise it looks good to me

**Comment by marieke6** [comment]
> Does the lower file actually run? The indentation looks strange in line 17-19?
> 
> Otherwise it looks good to me

Good catch not sure when this indentation happened it does look weird I'll double check

**Pull request merged**
