### PR TITLE
Add 2 papers on one shot learning and medical image analysis

### PR DESCRIPTION
**Pull request by Tecklenburg**
Issue fix: #304

Add interesting papers read this week implementation of insights needs to be done

### CODE REVIEW

**Review by emedema — CHANGES_REQUESTED** [review]
i'm not sure if we should upload papers like this. notes on them are fine IMO but we shouldn't bog down the repo with other people's work. just sending them in the discord would be fine

**Review by rogov-dvp — COMMENTED** [review]
Yeah, with emily on this. Link these in discord 👍

**Comment by Tecklenburg** [comment]
Thanks for the comment, I have removed the files and add my brief notes. I will try to implement these over the weekend:)

**Review by emedema — APPROVED** [review]
looks good!

**Pull request merged**
