### PR TITLE
TmI feedback added

### PR DESCRIPTION
**Pull request by marieke6**
Feedback added for the TMI groups

Issue fix: #63

### CODE REVIEW

**Review by emedema — COMMENTED** [review]
Good critiques just a few spelling and grammar mistakes to fix.

**Comment by marieke6** [comment]
Thanks Emily, fixed a few things so let me know if you spot anything else

**Comment by emedema** [comment]
The only other thing is you can remove the -

**Review by Tecklenburg — APPROVED** [review]
👍

**Pull request merged**
